# Generated by Django 2.2.6 on 2019-12-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191111_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like',
        ),
    ]
